### ISSUE TITLE
ModuleNotFoundError: No module named 'protoqa_evaluator.bert_scoring'

### ISSUE THREAD

**Issue by Frazier-Stewart** [iesl/protoqa-evaluator#4]
Dear protoqa team
I followed the readme to run roberta similarity mode. I installed the package with [_mlm-similarity_] script, and tried to import _TransformerScoringModel_ from bert_scoring. Then I get this error.
After browsing the code and history, I found that the roberta similarity has been removed from the code. I wonder why you remove this matric, and will it be updated in the future?
Zachary Li

**Comment by mboratko** [comment]
Thanks for your interest.

As described in the paper, the RoBERTa similarity model gave poor performance as it treats almost all things as similar to each other, and thus was not the recommended method.

The main reason it was removed for now was practical - it increased the dependencies and also required adjustments to the current evaluation framework that were not straightforward to resolve cleanly. While I am not against adding it back, at the moment it is not a priority due to the previously mentioned poor performance. I would be interested and open to alternative similarity measures, however, and this evaluator framework was intentionally designed to allow for such experimentation.

**Comment by zephyrli-coding** [comment]
OK Thank you~
